### ISSUE TITLE
Performance issues in the latest version (0.33.0)

### ISSUE THREAD

**Issue by chrxmvtik** [cnikolov/playwright-cluster#10]
Salut!

Today I noticed that latest version has finally a support of stealth plugin and wanted to try it out - however there has to be something wrong with it, because it leads to crawling fails for nearly each website.

Later then I disabled stealth plugin and tried to start crawler queue as usually, here are the results
![image](https://github.com/cnikolov/playwright-cluster/assets/49398549/22c5ca40-9c7f-430f-bf53-43cc5ceb6ebb)

I was really shocked that it took that long, so I decided to revert back to v0.28.0 and start the crawler once again, results below
![image](https://github.com/cnikolov/playwright-cluster/assets/49398549/9d4aca72-0f08-47a8-9ef6-a82735ad2e35)

Were there any significant changes to the code or anything that could cause those performance issues?

**Comment by cnikolov** [comment]
The stealth plugin itself seemed that is doing modifications too aggressively it might be because the site your are going through have some kind of code that crashes, just tried it with top 1mln and it works fine

**Comment by cnikolov** [comment]
To improve the performance change the concurrency type to page

**Comment by chrxmvtik** [comment]
> To improve the performance change the concurrency type to page
> 
> We fixed the browser and context concurrency but because its now fixed its doing a lot more. To get fast results use the page concurrency and before each task delete cookies and storage from the previous task.

Sorry for missing that out, I didn't mention that I am using the same config for both cases, which includes page concurrency. I have redone the tests with various configurations (keeping page cuncurrency) and every single time - latest version is about few times slower and throwing much more errors during crawling.

**Comment by cnikolov** [comment]
Try out 1.0.0 this is fully fixed. it was a problem related to playwright's latest changes.
