### ISSUE TITLE
improve: set useragent and viewport in puppeteer like style

### ISSUE THREAD

**Issue by methaqualon** [cnikolov/playwright-cluster#11]
common way to modify this metainfo is:

```
const iphone13 = devices['iPhone 13'];
const context = await browser.newContext({
  ...iphone13,
});
```

How we can do that in a cluster?

**Comment by cnikolov** [comment]
In the current version unfortunately the cluster doesn't support context settings. I personally think that this should be supported in the future I will add it to our agenda.

**Comment by methaqualon** [comment]
Of course, you just did asked me to post any improvements if i have them in previous ticket.
I’ll try to help in case, now l have some time to maybe create some of pull requests.

**Comment by cnikolov** [comment]
added additional options perPageOptions and pageOptions to the constructor of launch follow the alexa-1mln example for more info.

**Comment by cnikolov** [comment]
I will close the issue in any given time if it doesnt work feel free to open new ticket.
