### ISSUE TITLE
Cluster with custom playwright 

### ISSUE THREAD

**Issue by blackravenx** [cnikolov/playwright-cluster#9]
**Reporting a bug?**

**Error: Unable to launch browser for worker, error message: Cannot read properties of undefined (reading 'launch')`**

Hi, is there a way to use Playwright Cluster with PlaywrightExtra?

For example, following code will throw `Error: Unable to launch browser for worker, error message: Cannot read properties of undefined (reading 'launch')`

```
const example = async (task: TaskFunction) => {

  const customPlaywright = addExtra(playwright.chromium)

  customPlaywright.use(StealthPlugin())
  
    const cluster = await Cluster.launch({ 
    playwright: customPlaywright, //or just playwright.chromium 
    concurrency: Cluster.CONCURRENCY_BROWSER,
  //    ...etc
  })
 //... etc
 };
 
 example();
```
Everything works fine without if I don't provide custom playwright instance or any playwright browser at all 

System info: 
```
    "playwright": "^1.30.0",
    "playwright-cluster": "^0.26.0",
    "playwright-extra": "^4.3.5",
    "puppeteer-extra-plugin-stealth": "^2.11.1",
```

**Comment by methaqualon** [comment]
In SingleBrowserImplementation.js there are two mentions of Firefox, so there you should change browser
This library is just a quick hack of original one, puppeteer cluster

**Comment by cnikolov** [comment]
This should be now fixed follow the example customBrowser for more information and let me know if you see any other issues thanks for testing it.

**Comment by cnikolov** [comment]
@methaqualon Hi this project is not meant to mock the original author, quiet the opposite we are very thankful to Thomas for his incredible work in the clustering engine.

**Comment by methaqualon** [comment]
> @methaqualon Hi this project is not meant to mock the original author, quiet the opposite we are very thankful to Thomas for his incredible work in the clustering engine.

thank you too, because there are no another good ways to clusterize things like playwright
i'll test your commit tomorrow

**Comment by cnikolov** [comment]
@methaqualon  the point of the project is to solve business problems, if you see anything we can do to improve it submit a feed back or a ticket.

**Comment by cnikolov** [comment]
@blackravenx can you retest?

**Comment by methaqualon** [comment]
> @blackravenx can you retest?

works perfectly
